networks:
  default:
    external:
      name: int371-network
services:
  backend:
    container_name: backend_dev
    build: .
    image: ghcr.io/int371-numjai/namjai-be:dev
    volumes:
      - ~/backend/dev/fdn_documents:/fdn_documents
      - ~/backend/dev/foundation:/foundation
      - ~/backend/dev/web_resources:/web_resources